### ISSUE TITLE
Test `test_1_update_tld_names (tld.test.TldTest)` is failing while creating .deb package.

### ISSUE THREAD

**Issue by curusarn** [barseghyanartur/tld#19]
I'm creating .deb package and `test_1_update_tld_names (tld.test.TldTest)` test is failing.

What I did:
1. `pip download tld`
2. `py2dsc`
3. `cd deb_dist/tld-0.7.9`
4. `dpkg-buildpackage`

This is the second half of the `dpkg-buildpackage` output. 
(Full output: https://gist.github.com/curusarn/6569fb9f4ec899f2f115a89a01cc11ff.)
```
...
test_0_tld_names_loaded (tld.test.TldTest)
Inner. ... ok
test_1_update_tld_names (tld.test.TldTest)
Inner. ... FAIL
test_2_good_patterns_pass (tld.test.TldTest)
Inner. ... ok
test_3_bad_patterns_pass (tld.test.TldTest)
Inner. ... ok
test_4_override_settings (tld.test.TldTest)
Inner. ... ok
test_5_good_patterns_pass_parsed_object (tld.test.TldTest)
Inner. ... ok
test_6_override_full_names_path (tld.test.TldTest)
Inner. ... ok

======================================================================
FAIL: test_1_update_tld_names (tld.test.TldTest)
Inner.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tld/test.py", line 35, in inner
    result = func(self, *args, **kwargs)
  File "tld/test.py", line 155, in test_1_update_tld_names
    self.assertTrue(res)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.051s

FAILED (failures=1)
E: pybuild pybuild:256: test: plugin distutils failed with: exit code=1: cd /tmp/tld_packaging/deb_dist/tld-0.7.9/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
dh_auto_test: pybuild --test -i python{version} -p 2.7 --dir . returned exit code 13
debian/rules:7: recipe for target 'build' failed
make: *** [build] Error 13
dpkg-buildpackage: error: debian/rules build gave error exit status 2

```

**Comment by barseghyanartur** [comment]
@curusarn:

It does't fall in standard scenarios. Could I get access the source code of your deb package?

**Comment by curusarn** [comment]
I have created a repo with the source: https://github.com/curusarn/tld-deb-source

**Comment by barseghyanartur** [comment]
@curusarn:

I'll check it soon.

**Comment by Lamberk** [comment]
Have the same problem. I am trying to make deb package with `python-stdeb`
`python setup.py --command-packages=stdeb.command bdist_deb`

**Comment by barseghyanartur** [comment]
I get different error:

```bash
python setup.py --command-packages=stdeb.command bdist_deb
```

```text
running bdist_deb
running sdist_dsc
running egg_info
writing top-level names to src/tld.egg-info/top_level.txt
writing dependency_links to src/tld.egg-info/dependency_links.txt
writing requirements to src/tld.egg-info/requires.txt
writing src/tld.egg-info/PKG-INFO
reading manifest file 'src/tld.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/tld.egg-info/SOURCES.txt'
running sdist
running check
creating tld-0.7.9
creating tld-0.7.9/src
creating tld-0.7.9/src/tld
creating tld-0.7.9/src/tld.egg-info
creating tld-0.7.9/src/tld/bin
creating tld-0.7.9/src/tld/commands
creating tld-0.7.9/src/tld/res
creating tld-0.7.9/src/tld/res/old
creating tld-0.7.9/src/tld/sources
copying files to tld-0.7.9...
copying MANIFEST.in -> tld-0.7.9
copying README.rst -> tld-0.7.9
copying setup.cfg -> tld-0.7.9
copying setup.py -> tld-0.7.9
copying src/tld/__init__.py -> tld-0.7.9/src/tld
copying src/tld/base.py -> tld-0.7.9/src/tld
copying src/tld/conf.py -> tld-0.7.9/src/tld
copying src/tld/defaults.py -> tld-0.7.9/src/tld
copying src/tld/exceptions.py -> tld-0.7.9/src/tld
copying src/tld/helpers.py -> tld-0.7.9/src/tld
copying src/tld/test.py -> tld-0.7.9/src/tld
copying src/tld/utils.py -> tld-0.7.9/src/tld
copying src/tld.egg-info/PKG-INFO -> tld-0.7.9/src/tld.egg-info
copying src/tld.egg-info/SOURCES.txt -> tld-0.7.9/src/tld.egg-info
copying src/tld.egg-info/dependency_links.txt -> tld-0.7.9/src/tld.egg-info
copying src/tld.egg-info/requires.txt -> tld-0.7.9/src/tld.egg-info
copying src/tld.egg-info/top_level.txt -> tld-0.7.9/src/tld.egg-info
copying src/tld/bin/update-tld-names -> tld-0.7.9/src/tld/bin
copying src/tld/commands/__init__.py -> tld-0.7.9/src/tld/commands
copying src/tld/commands/update_tld_names.py -> tld-0.7.9/src/tld/commands
copying src/tld/res/effective_tld_names.dat.txt -> tld-0.7.9/src/tld/res
copying src/tld/res/old/effective_tld_names-2013-04-22.dat.txt -> tld-0.7.9/src/tld/res/old
copying src/tld/res/old/effective_tld_names-2015-07-19.dat.txt -> tld-0.7.9/src/tld/res/old
copying src/tld/sources/__init__.py -> tld-0.7.9/src/tld/sources
copying src/tld/sources/mozilla.py -> tld-0.7.9/src/tld/sources
Writing tld-0.7.9/setup.cfg
Creating tar archive
removing 'tld-0.7.9' (and everything under it)
CALLING dpkg-source -b tld-0.7.9 tld_0.7.9.orig.tar.gz (in dir deb_dist)
dpkg-source: info: using options from tld-0.7.9/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building tld using existing ./tld_0.7.9.orig.tar.gz
dpkg-source: info: building tld in tld_0.7.9-1.debian.tar.xz
dpkg-source: info: building tld in tld_0.7.9-1.dsc
dpkg-buildpackage: source package tld
dpkg-buildpackage: source version 0.7.9-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Artur Barseghyan <artur.barseghyan@gmail.com>
 dpkg-source --before-build tld-0.7.9
dpkg-source: info: using options from tld-0.7.9/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-checkbuilddeps: error: Unmet build dependencies: python3-all
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    'six>=1.9'
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/delusionalinsanity/.virtualenvs/tld/lib/python3.5/site-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/delusionalinsanity/.virtualenvs/tld/lib/python3.5/site-packages/stdeb/command/sdist_dsc.py", line 140, in run
    remove_expanded_source_dir=self.remove_expanded_source_dir,
  File "/home/delusionalinsanity/.virtualenvs/tld/lib/python3.5/site-packages/stdeb/util.py", line 1421, in build_dsc
    dpkg_genchanges(cwd=fullpath_repackaged_dirname)
  File "/home/delusionalinsanity/.virtualenvs/tld/lib/python3.5/site-packages/stdeb/util.py", line 538, in dpkg_genchanges
    process_command(args,cwd=cwd)
  File "/home/delusionalinsanity/.virtualenvs/tld/lib/python3.5/site-packages/stdeb/util.py", line 183, in process_command
    check_call(args, cwd=cwd)
  File "/home/delusionalinsanity/.virtualenvs/tld/lib/python3.5/site-packages/stdeb/util.py", line 46, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 3
```

**Comment by barseghyanartur** [comment]
Sorry, I could fit that using 

```bash
sudo apt-get install python3-all 
```

And further, I managed to [build it](https://drive.google.com/drive/folders/1RHv1bx3Ur3xbEitdq1w6xaxmFH2s_NmT?usp=sharing).

**Comment by barseghyanartur** [comment]
However, I didn't do pip download.

What I did (from the project root):

```bash
python setup.py sdist bdist_wheel
py2dsc-deb dist/tld-0.7.9.tar.gz
```

After that I had a directory in root named ``deb_dist`` with (several) files, but these 2 in particular:

- python-tld_0.7.9-1_all.deb
- python3-tld_0.7.9-1_all.deb

**Comment by barseghyanartur** [comment]
@curusarn, @Lamberk:

Please, let me know if it works for you.
