### ISSUE TITLE
py27 import error

### ISSUE THREAD

**Issue by Yomguithereal** [barseghyanartur/tld#73]
Hello @barseghyanartur, sorry for coming back :)

Here is the error you get if you try to install `0.11.7` on py27:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Yomgui/.pyenv/versions/test27/lib/python2.7/site-packages/tld/__init__.py", line 7, in <module>
    from .utils import get_fld, get_tld, get_tld_names, is_tld, parse_tld, Result, update_tld_names
  File "/Users/Yomgui/.pyenv/versions/test27/lib/python2.7/site-packages/tld/utils.py", line 10, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named backports.functools_lru_cache
```

**Comment by barseghyanartur** [comment]
That's strange. It's listed in setup requires.

**Comment by barseghyanartur** [comment]
Ah, I see. I accidentally added it to tests require. Will fix that.

**Comment by Yomguithereal** [comment]
Thanks @barseghyanartur

**Comment by barseghyanartur** [comment]
Done.

**Comment by Yomguithereal** [comment]
Thanks
