### ISSUE TITLE
get_fld fails for s.amazon-adsystem.com

### ISSUE THREAD

**Issue by rosstex** [barseghyanartur/tld#85]
```
>>> import tld
>>> tld.get_fld("s.amazon-adsystem.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rapt/anaconda3/envs/py38/lib/python3.8/site-packages/tld/utils.py", line 432, in get_fld
    domain_parts, non_zero_i, parsed_url = process_url(
  File "/home/rapt/anaconda3/envs/py38/lib/python3.8/site-packages/tld/utils.py", line 327, in process_url
    raise TldBadUrl(url=url)
tld.exceptions.TldBadUrl: Is not a valid URL s.amazon-adsystem.com!
```

**Comment by rosstex** [comment]
Ignore this, I forgot to fix the protocol again..... sorry
